### ISSUE TITLE
Salt Water

### ISSUE THREAD

**Issue by Fumblesneeze** [tenbom/BetterTerrain#3]
Hey, I made a mod that makes lakes freeze in cold temps: https://github.com/Fumblesneeze/RimIce

For this I've detoured the BeachMaker so that it places SaltWaterShallow and SaltWaterDeep, basically same Terrains as normal water, just so that it doesn't freeze.

Would you also switch to creating salt water for beaches?

**Comment by DenJur** [comment]
Unfortunately, I haven't heard anything from @tenbom in over a month so I am afraid this mod might be dead at this point. I can accept a PR if you want to make one but at this point it seems to be pointless as I lack artistic talent and time to continue development of this mod on my own.

**Comment by DenJur** [comment]
Solved by #4
Thank you for the commit.
